server:
  port: 8082

#spring:
#  shardingsphere:
#    datasource:
#      ds0:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://47.112.139.55:8200/shardingsphere-test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#        password: chensiwei22Welcome
#        type: com.zaxxer.hikari.HikariDataSource
#        username: lk
#      ds1:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://47.112.139.55:8200/shardingsphere-test2?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#        password: chensiwei22Welcome
#        type: com.zaxxer.hikari.HikariDataSource
#        username: lk
#      names: ds0,ds1
#    props:
#      sql:
#        show: true
#    sharding:
#      default-database-strategy:
#        inline:
#          algorithm-expression: ds$->{id % 2}
#          sharding-column: id
#      master-slave-rules:
#        ms-1:
#          master-data-source-name: ds0
#      tables:
#        t_user:
#          actual-data-nodes: ds$->{0..1}.t_order_$->{0..2}
#          key-generator:
#            column: id
#            type: SNOWFLAKE
#          table-strategy:
#            inline:
#              algorithm-expression: t_user_$->{id % 3}
#              sharding-column: id
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.139.55:8200/shardingsphere-test2?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    password: chensiwei22Welcome
    type: com.zaxxer.hikari.HikariDataSource
    username: lk
